unit ibSHSQLs;

interface

const
// -> Common -------------------------------------------------------------------
  SQL_CREATE_DATABASE_PARAMS: array[0..3] of string = (
    'USER ''%s''',
    'PASSWORD ''%s''',
    'PAGE_SIZE %s',
    'DEFAULT CHARACTER SET %s');

  SQL_GET_DB_CHARSET: array[0..2] of string = (
    'SELECT',
    '  RDB$CHARACTER_SET_NAME',
    'FROM RDB$DATABASE');

  SQL_EXISTS_PRECISION: array[0..8] of string = (
    'SELECT',
    '  1 AS RESULT',
    'FROM RDB$DATABASE RD',
    'WHERE EXISTS (',
    '  SELECT RF.*',
    '  FROM RDB$RELATION_FIELDS RF',
    '  WHERE (RF.RDB$RELATION_NAME = ''RDB$FIELDS'') AND',
    '        (RF.RDB$FIELD_NAME = ''RDB$FIELD_PRECISION'')',
    '  )');

  SQL_EXISTS_PROC_PARAMDOMAINS: array[0..8] of string = (
    'SELECT',
    '  1 AS RESULT',
    'FROM RDB$DATABASE RD',
    'WHERE EXISTS (',
    '  SELECT RF.*',
    '  FROM RDB$RELATION_FIELDS RF',
    '  WHERE (RF.RDB$RELATION_NAME = ''RDB$PROCEDURE_PARAMETERS'') AND',
    '        (RF.RDB$FIELD_NAME = ''RDB$PARAMETER_MECHANISM'')',
    '  )');

  SQL_GET_DIMENSIONS: array[0..5] of string = (
    'SELECT',
    '  FD.RDB$LOWER_BOUND AS LOWER_BOUND,',
    '  FD.RDB$UPPER_BOUND AS UPPER_BOUND',
    'FROM RDB$FIELD_DIMENSIONS FD',
    'WHERE FD.RDB$FIELD_NAME = :FIELD_NAME',
    'ORDER BY FD.RDB$DIMENSION');

  SQL_GET_RECORD_COUNT: array[0..1] of string = (
    'SELECT COUNT(*)',
    'FROM %s');

  SQL_GET_RECORD_COUNT_FROM_SQL_TEXT: array[0..0] of string = (
    'SELECT COUNT(*) %s');

  SQL_GET_CHANGE_COUNT: array[0..4] of string = (
    'SELECT',
    '  R.RDB$FORMAT',
    'FROM RDB$RELATIONS R',
    'WHERE RDB$RELATION_NAME = :RELATION_NAME AND',
    '      RDB$VIEW_SOURCE IS NULL');

// -> Domain -------------------------------------------------------------------
  SQL_GET_DOMAIN_NAME_LIST: array[0..4] of string = (
    'SELECT',
    '  D.RDB$FIELD_NAME AS NAME',
    'FROM RDB$FIELDS D',
    'WHERE (D.RDB$SYSTEM_FLAG IS NULL OR D.RDB$SYSTEM_FLAG <> 1) AND',
    '      (NOT RDB$FIELD_NAME STARTING WITH ''RDB$'')');

  SQL_GET_SYSTEM_DOMAIN_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  D.RDB$FIELD_NAME AS NAME',
    'FROM RDB$FIELDS D',
    'WHERE (D.RDB$SYSTEM_FLAG = 1)');

  SQL_EXISTS_DOMAIN_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$FIELDS D',
    'WHERE D.RDB$FIELD_NAME = :FIELD_NAME');

  SQL_INIT_DOMAIN1: array[0..17] of string = (
    'SELECT',
    '  F.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  F.RDB$DEFAULT_SOURCE AS DEFAULT_EXPRESSION,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',  //'  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  0 AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$VALIDATION_SOURCE AS CHECK_CONSTRAINT,',
    '  F.RDB$DIMENSIONS AS ARRAY_DIM',
    'FROM RDB$FIELDS F',
    'WHERE F.RDB$FIELD_NAME = :DOMAIN_NAME');

   SQL_INIT_DOMAIN3: array[0..17] of string = (
    'SELECT',
    '  F.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  F.RDB$DEFAULT_SOURCE AS DEFAULT_EXPRESSION,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$VALIDATION_SOURCE AS CHECK_CONSTRAINT,',
    '  F.RDB$DIMENSIONS AS ARRAY_DIM',
    'FROM RDB$FIELDS F',
    'WHERE F.RDB$FIELD_NAME = :DOMAIN_NAME');

  SQL_GET_COMMENT_DOMAIN: array[0..3] of string = (
    'SELECT',
    '  F.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$FIELDS F',
    'WHERE F.RDB$FIELD_NAME = ''%s'';');

  SQL_SET_COMMENT_DOMAIN: array[0..2] of string = (
    'UPDATE RDB$FIELDS F SET F.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE F.RDB$FIELD_NAME = ''%s'';');

  SQL_SET_COMMENT_DOMAIN_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$FIELDS F',
    'SET F.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE F.RDB$FIELD_NAME = ''%s'';');

  SQL_GET_DOMAINS_WITH_COMMENTS: string =
    'SELECT '+
    '  F.RDB$FIELD_NAME '+
    'FROM RDB$FIELDS F '+
    'WHERE NOT F.RDB$DESCRIPTION IS NULL';

// -> Table --------------------------------------------------------------------
  SQL_GET_TABLE_NAME_LIST: array[0..4] of string = (
    'SELECT',
    '  T.RDB$RELATION_NAME AS NAME',
    'FROM RDB$RELATIONS T',
    'WHERE (T.RDB$SYSTEM_FLAG IS NULL OR T.RDB$SYSTEM_FLAG <> 1) AND',
    '      (T.RDB$VIEW_BLR IS NULL)');

  SQL_EXISTS_TABLE_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$RELATIONS T',
    'WHERE T.RDB$RELATION_NAME = :RELATION_NAME');

  SQL_GET_SYSTEM_TABLE_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  T.RDB$RELATION_NAME AS NAME',
    'FROM RDB$RELATIONS T',
//  'WHERE (T.RDB$SYSTEM_FLAG = 1) AND (T.RDB$RELATION_NAME STARTING WITH ''RDB$'')'
     'WHERE (T.RDB$SYSTEM_FLAG = 1) '

    );


  SQL_GET_SYSTEM_TABLE_TMP_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  T.RDB$RELATION_NAME AS NAME',
    'FROM RDB$RELATIONS T',
    'WHERE (T.RDB$SYSTEM_FLAG = 1) AND (T.RDB$RELATION_NAME STARTING WITH ''TMP$'')');

  SQL_INIT_TABLE: array[0..0] of string = (
    'SELECT'#13#10+
    '  R.RDB$OWNER_NAME AS OWNER_NAME,'#13#10+
    '  R.RDB$DESCRIPTION AS DESCRIPTION,'#13#10+
    '  R.RDB$EXTERNAL_FILE  AS EXTERNAL_FILE'#13#10+
    'FROM RDB$RELATIONS R'#13#10+
    'WHERE R.RDB$RELATION_NAME = :RELATION_NAME AND'#13#10+
    '      R.RDB$VIEW_SOURCE IS NULL');

  SQL_INIT_TABLE_FIELDS1: array[0..28] of string = (
    'SELECT',
    '  F.RDB$FIELD_NAME AS OBJECT_NAME,',
    '  F.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  F.RDB$DEFAULT_SOURCE AS DEFAULT_EXPRESSION,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  0  AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$VALIDATION_SOURCE AS CHECK_CONSTRAINT,',
    '  F.RDB$DIMENSIONS AS ARRAY_DIM,',
    '  F.RDB$COMPUTED_SOURCE AS COMPUTED_SOURCE,',
    '  RF.RDB$FIELD_NAME AS F_FIELD_NAME,',
    '  RF.RDB$RELATION_NAME AS F_TABLE_NAME,',
    '  RF.RDB$DESCRIPTION AS F_DESCRIPTION,',
    '  RF.RDB$NULL_FLAG AS F_NOT_NULL,',
    '  RF.RDB$DEFAULT_SOURCE AS F_DEFAULT_EXPRESSION,',
    '  RF.RDB$FIELD_SOURCE AS F_BASED_ON_DOMAIN,',
    '  RF.RDB$COLLATION_ID AS F_COLLATE_ID',
    'FROM RDB$RELATION_FIELDS RF',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE',
    'WHERE RF.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY RF.RDB$FIELD_POSITION');

  SQL_INIT_TABLE_FIELDS3: array[0..28] of string = (
    'SELECT',
    '  F.RDB$FIELD_NAME AS OBJECT_NAME,',
    '  F.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  F.RDB$DEFAULT_SOURCE AS DEFAULT_EXPRESSION,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$VALIDATION_SOURCE AS CHECK_CONSTRAINT,',
    '  F.RDB$DIMENSIONS AS ARRAY_DIM,',
    '  F.RDB$COMPUTED_SOURCE AS COMPUTED_SOURCE,',
    '  RF.RDB$FIELD_NAME AS F_FIELD_NAME,',
    '  RF.RDB$RELATION_NAME AS F_TABLE_NAME,',
    '  RF.RDB$DESCRIPTION AS F_DESCRIPTION,',
    '  RF.RDB$NULL_FLAG AS F_NOT_NULL,',
    '  RF.RDB$DEFAULT_SOURCE AS F_DEFAULT_EXPRESSION,',
    '  RF.RDB$FIELD_SOURCE AS F_BASED_ON_DOMAIN,',
    '  RF.RDB$COLLATION_ID AS F_COLLATE_ID',
    'FROM RDB$RELATION_FIELDS RF',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE',
    'WHERE RF.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY RF.RDB$FIELD_POSITION');

  SQL_GET_TABLE_FIELDS: array[0..4] of string = (
    'SELECT',
    '  RF.RDB$FIELD_NAME AS F_FIELD_NAME',
    'FROM RDB$RELATION_FIELDS RF',
    'WHERE RF.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY RF.RDB$FIELD_POSITION');

  SQL_GET_TABLE_FIELDS1: array[0..23] of string = (
    'SELECT',
    '  RF.RDB$FIELD_NAME AS F_FIELD_NAME,',
//    '  F.RDB$FIELD_NAME AS OBJECT_NAME,',
//    '  F.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  F.RDB$DEFAULT_SOURCE AS DEFAULT_EXPRESSION,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  0  AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$VALIDATION_SOURCE AS CHECK_CONSTRAINT,',
    '  F.RDB$DIMENSIONS AS ARRAY_DIM,',
    '  F.RDB$COMPUTED_SOURCE AS COMPUTED_SOURCE,',
//    '  RF.RDB$RELATION_NAME AS F_TABLE_NAME,',
//    '  RF.RDB$DESCRIPTION AS F_DESCRIPTION,',
    '  RF.RDB$NULL_FLAG AS F_NOT_NULL,',
    '  RF.RDB$DEFAULT_SOURCE AS F_DEFAULT_EXPRESSION,',
//    '  RF.RDB$FIELD_SOURCE AS F_BASED_ON_DOMAIN,',
    '  RF.RDB$COLLATION_ID AS F_COLLATE_ID',
    'FROM RDB$RELATION_FIELDS RF',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE',
    'WHERE RF.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY RF.RDB$FIELD_POSITION');

  SQL_GET_TABLE_FIELDS3: array[0..23] of string = (
    'SELECT',
    '  RF.RDB$FIELD_NAME AS F_FIELD_NAME,',
//    '  F.RDB$FIELD_NAME AS OBJECT_NAME,',
//    '  F.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  F.RDB$DEFAULT_SOURCE AS DEFAULT_EXPRESSION,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$VALIDATION_SOURCE AS CHECK_CONSTRAINT,',
    '  F.RDB$DIMENSIONS AS ARRAY_DIM,',
    '  F.RDB$COMPUTED_SOURCE AS COMPUTED_SOURCE,',
//    '  RF.RDB$RELATION_NAME AS F_TABLE_NAME,',
//    '  RF.RDB$DESCRIPTION AS F_DESCRIPTION,',
    '  RF.RDB$NULL_FLAG AS F_NOT_NULL,',
    '  RF.RDB$DEFAULT_SOURCE AS F_DEFAULT_EXPRESSION,',
//    '  RF.RDB$FIELD_SOURCE AS F_BASED_ON_DOMAIN,',
    '  RF.RDB$COLLATION_ID AS F_COLLATE_ID',
    'FROM RDB$RELATION_FIELDS RF',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE',
    'WHERE RF.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY RF.RDB$FIELD_POSITION');

  SQL_INIT_TABLE_TRIGGERS: array[0..8] of string = (
    'SELECT',
    '  T.RDB$TRIGGER_NAME AS TRIGGER_NAME',
    'FROM RDB$TRIGGERS T',
    '  LEFT JOIN RDB$CHECK_CONSTRAINTS C ON C.RDB$TRIGGER_NAME = T.RDB$TRIGGER_NAME',
    'WHERE C.RDB$TRIGGER_NAME IS NULL AND',
    '      T.RDB$TRIGGER_SOURCE IS NOT NULL AND',
    '      ((T.RDB$SYSTEM_FLAG = 0) OR (T.RDB$SYSTEM_FLAG IS NULL)) AND',
    '      (T.RDB$RELATION_NAME = :RELATION_NAME)',
    'ORDER BY T.RDB$TRIGGER_TYPE, T.RDB$TRIGGER_SEQUENCE, T.RDB$TRIGGER_NAME');

  SQL_INIT_TABLE_CONSTRAINTS_PRIMARY: array[0..5] of string = (
    'SELECT',
    '  RC.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    'WHERE RC.RDB$CONSTRAINT_TYPE = ''PRIMARY KEY'' AND',
    '      RC.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY RC.RDB$CONSTRAINT_NAME');

  SQL_INIT_TABLE_CONSTRAINTS_FOREIGN: array[0..5] of string = (
    'SELECT',
    '  RC.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    'WHERE RC.RDB$CONSTRAINT_TYPE = ''FOREIGN KEY'' AND',
    '      RC.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY RC.RDB$CONSTRAINT_NAME');

  SQL_INIT_TABLE_CONSTRAINTS_UNIQUE: array[0..5] of string = (
    'SELECT',
    '  RC.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    'WHERE RC.RDB$CONSTRAINT_TYPE = ''UNIQUE'' AND',
    '      RC.RDB$RELATION_NAME = :RELATION_NAME ',
    'ORDER BY RC.RDB$CONSTRAINT_NAME');

  SQL_INIT_TABLE_CONSTRAINTS_CHECK: array[0..5] of string = (
    'SELECT',
    '  RC.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    'WHERE RC.RDB$CONSTRAINT_TYPE = ''CHECK'' AND',
    '      RC.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY RC.RDB$CONSTRAINT_NAME');

  SQL_INIT_TABLE_INDICES: array[0..4] of string = (
    'SELECT',
    '  IDX.RDB$INDEX_NAME AS INDEX_NAME ',
    'FROM RDB$INDICES IDX',
    'WHERE IDX.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY IDX.RDB$INDEX_NAME');

  SQL_GET_COMMENT_TABLE: array[0..3] of string = (
    'SELECT',
    '  R.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$RELATIONS R',
    'WHERE R.RDB$RELATION_NAME = ''%s'';');

  SQL_SET_COMMENT_TABLE: array[0..2] of string = (
    'UPDATE RDB$RELATIONS R SET R.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE R.RDB$RELATION_NAME = ''%s'';');

  SQL_SET_COMMENT_TABLE_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$RELATIONS R',
    'SET R.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE R.RDB$RELATION_NAME = ''%s'';');

  SQL_GET_TABLES_WITH_COMMENTS: string =
    'SELECT R.RDB$RELATION_NAME FROM RDB$RELATIONS R'#13#10+
    'WHERE'#13#10+
    '(R.RDB$SYSTEM_FLAG IS NULL OR R.RDB$SYSTEM_FLAG <> 1) AND'#13#10+
    '(R.RDB$VIEW_BLR IS NULL) AND'#13#10+
    '(NOT R.RDB$DESCRIPTION  IS NULL OR'#13#10+
    '(Exists(Select * from RDB$RELATION_FIELDS RF WHERE'#13#10+
    'RF.RDB$RELATION_NAME = R.RDB$RELATION_NAME and not RF.RDB$DESCRIPTION IS NULL)))';
    
// -> Field --------------------------------------------------------------------
  SQL_GET_COMMENT_FIELD: array[0..3] of string = (
    'SELECT',
    '  RF.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$RELATION_FIELDS RF',
    'WHERE (RF.RDB$FIELD_NAME = ''%s'') AND (RF.RDB$RELATION_NAME = ''%s'');');

  SQL_SET_COMMENT_FIELD: array[0..2] of string = (
    'UPDATE RDB$RELATION_FIELDS RF SET RF.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE (RF.RDB$FIELD_NAME = ''%s'') AND (RF.RDB$RELATION_NAME = ''%s'');');

  SQL_GET_FIELDS_WITH_COMMENTS: string =
    'SELECT  RF.RDB$RELATION_NAME,RF.RDB$FIELD_NAME'#13#10+
    'FROM RDB$RELATION_FIELDS RF'#13#10+
    'WHERE NOT RF.RDB$DESCRIPTION IS  NULL';
  SQL_GET_PROCPARAMS_WITH_COMMENTS: string =
    'SELECT  PP.RDB$PROCEDURE_NAME,PP.RDB$PARAMETER_NAME'#13#10+
    'FROM RDB$PROCEDURE_PARAMETERS PP'#13#10+
    'WHERE NOT PP.RDB$DESCRIPTION IS NULL'
    ;

  SQL_SET_COMMENT_FIELD_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$RELATION_FIELDS RF',
    'SET RF.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE (RF.RDB$FIELD_NAME = ''%s'') AND (RF.RDB$RELATION_NAME = ''%s'');');

  SQL_GET_COMMENT_PROC_PARAM: array[0..3] of string = (
    'SELECT',
    '  PP.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$PROCEDURE_PARAMETERS PP',
    'WHERE (PP.RDB$PARAMETER_NAME = ''%s'') AND (PP.RDB$PROCEDURE_NAME = ''%s'');');

  SQL_SET_COMMENT_PROC_PARAM: array[0..2] of string = (
    'UPDATE RDB$PROCEDURE_PARAMETERS PP SET PP.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE (PP.RDB$PARAMETER_NAME = ''%s'') AND (PP.RDB$PROCEDURE_NAME = ''%s'');');

  SQL_SET_COMMENT_PROC_PARAM_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$PROCEDURE_PARAMETERS PP',
    'SET PP.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE (PP.RDB$PARAMETER_NAME = ''%s'') AND (PP.RDB$PROCEDURE_NAME = ''%s'');');

  SQL_SET_FIELD_POSITION1: array[0..3] of string = (
    'UPDATE RDB$RELATION_FIELDS',
    'SET RDB$FIELD_POSITION = %d',
    'WHERE (RDB$RELATION_NAME = ''%s'') AND',
    '      (RDB$FIELD_NAME = ''%s'');');

  SQL_SET_FIELD_POSITION3: array[0..1] of string = (
    'ALTER TABLE %s',
    'ALTER %s POSITION %d;');


// -> Constraint ---------------------------------------------------------------
  SQL_GET_CONSTRAINT_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  RC.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    'WHERE RC.RDB$CONSTRAINT_TYPE <> ''NOT NULL''');

  SQL_EXISTS_CONSTRAINT_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    'WHERE RC.RDB$CONSTRAINT_NAME = :CONSTRAINT_NAME');

  SQL_INIT_CONSTRAINT: array[0..5] of string = (
    'SELECT',
    '  RC.RDB$CONSTRAINT_TYPE AS CONSTRAINT_TYPE,',
    '  RC.RDB$RELATION_NAME AS TABLE_NAME,',
    '  RC.RDB$INDEX_NAME AS INDEX_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    'WHERE RC.RDB$CONSTRAINT_NAME = :CONSTRAINT_NAME');

  SQL_INIT_CONSTRAINT_INDEX: array[0..3] of string = (
    'SELECT',
    '  IDX.RDB$INDEX_TYPE AS ASCENDING_',
    'FROM RDB$INDICES IDX',
    'WHERE IDX.RDB$INDEX_NAME = :INDEX_NAME');

  SQL_INIT_CONSTRAINT_FIELDS: array[0..4] of string = (
    'SELECT',
    '  IDXS.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$INDEX_SEGMENTS IDXS',
    'WHERE IDXS.RDB$INDEX_NAME = :INDEX_NAME',
    'ORDER BY IDXS.RDB$FIELD_POSITION');

  SQL_INIT_CONSTRAINT_REFERENCE: array[0..5] of string = (
    'SELECT',
    '  RC.RDB$CONST_NAME_UQ AS CONST_NAME_UQ,',
    '  RC.RDB$UPDATE_RULE AS UPDATE_RULE,',
    '  RC.RDB$DELETE_RULE AS DELETE_RULE',
    'FROM RDB$REF_CONSTRAINTS RC',
    'WHERE RC.RDB$CONSTRAINT_NAME = :CONSTRAINT_NAME');


  SQL_INIT_CONSTRAINT_CHECK: array[0..5] of string = (
    'SELECT',
    '  T.RDB$TRIGGER_SOURCE AS SOURCE',
    'FROM RDB$TRIGGERS T',
    '  JOIN RDB$CHECK_CONSTRAINTS CC ON CC.RDB$TRIGGER_NAME = T.RDB$TRIGGER_NAME',
    'WHERE T.RDB$TRIGGER_TYPE = 1 AND',
    '      CC.RDB$CONSTRAINT_NAME = :CONSTRAINT_NAME');

// -> Index --------------------------------------------------------------------
  SQL_GET_INDEX_NAME_LIST: array[0..7] of string = (
    'SELECT',
    '  IDX.RDB$INDEX_NAME AS OBJECT_NAME',
    'FROM RDB$INDICES IDX',
    'WHERE (IDX.RDB$SYSTEM_FLAG IS NULL OR IDX.RDB$SYSTEM_FLAG <> 1) AND',
    '      NOT IDX.RDB$INDEX_NAME STARTING WITH ''RDB$'' AND',
    '      NOT EXISTS (SELECT 1',
    '                  FROM RDB$RELATION_CONSTRAINTS RC',
    '                  WHERE RC.RDB$INDEX_NAME = IDX.RDB$INDEX_NAME)');

  SQL_EXISTS_INDEX_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$INDICES IDX',
    'WHERE IDX.RDB$INDEX_NAME = :INDEX_NAME');

  SQL_INIT_INDEX: array[0..9] of string = (
    'SELECT',
    '  IDX.RDB$RELATION_NAME AS TABLE_NAME,',
    '  IDX.RDB$UNIQUE_FLAG AS UNIQUE_FLAG,',
    '  IDX.RDB$INDEX_TYPE AS ASCENDING_,',
    '  IDX.RDB$INDEX_INACTIVE AS IN_ACTIVE,',
    '  IDX.RDB$EXPRESSION_SOURCE AS EXPRESSION_SOURCE,',
    '  IDX.RDB$STATISTICS AS STATISTIC,',
    '  IDX.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$INDICES IDX',
    'WHERE IDX.RDB$INDEX_NAME = :INDEX_NAME');

  SQL_INIT_INDEX_FIELDS: array[0..4] of string = (
    'SELECT',
    '  IDXS.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$INDEX_SEGMENTS IDXS',
    'WHERE IDXS.RDB$INDEX_NAME = :INDEX_NAME',
    'ORDER BY IDXS.RDB$FIELD_POSITION');

  SQL_GET_COMMENT_INDEX: array[0..3] of string = (
    'SELECT',
    '  I.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$INDICES I',
    'WHERE I.RDB$INDEX_NAME = ''%s'';');

  SQL_SET_COMMENT_INDEX: array[0..2] of string = (
    'UPDATE RDB$INDICES I SET I.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE I.RDB$INDEX_NAME = ''%s'';');

  SQL_SET_COMMENT_INDEX_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$INDICES I',
    'SET I.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE I.RDB$INDEX_NAME = ''%s'';');

  SQL_GET_STATISTICS: array[0..3] of string = (
    'SELECT',
    '  IDX.RDB$STATISTICS AS STATISTIC',
    'FROM RDB$INDICES IDX',
    'WHERE IDX.RDB$INDEX_NAME = :INDEX_NAME');

  SQL_SET_STATISTICS: array[0..0] of string = (
    'SET STATISTICS INDEX %s');

  SQL_IS_CONSTRAINT_INDEX: array[0..2] of string = (
   'SELECT COUNT(*) ',
   'FROM RDB$RELATION_CONSTRAINTS',
   'WHERE RDB$INDEX_NAME=:INDEX_NAME'
  );

// -> View ---------------------------------------------------------------------
  SQL_GET_VIEW_NAME_LIST: array[0..5] of string = (
    'SELECT',
    '  V.RDB$RELATION_NAME AS NAME',
    'FROM RDB$RELATIONS V',
    'WHERE (V.RDB$SYSTEM_FLAG IS NULL OR V.RDB$SYSTEM_FLAG <> 1) AND',
    '      (NOT V.RDB$VIEW_BLR IS NULL) AND',
    '      (V.RDB$FLAGS = 1)');


  SQL_GET_VIEWS_WITH_COMMENTS:string =

    'SELECT R.RDB$RELATION_NAME FROM RDB$RELATIONS R'#13#10+
    'WHERE'#13#10+
    '(R.RDB$SYSTEM_FLAG IS NULL OR R.RDB$SYSTEM_FLAG <> 1) AND'#13#10+
    '(NOT R.RDB$VIEW_BLR IS NULL)AND (R.RDB$FLAGS = 1) AND'#13#10+
    '(NOT R.RDB$DESCRIPTION  IS NULL OR'#13#10+
    '(Exists(Select * from RDB$RELATION_FIELDS RF WHERE'#13#10+
    'RF.RDB$RELATION_NAME = R.RDB$RELATION_NAME and not RF.RDB$DESCRIPTION IS NULL)))';


  SQL_EXISTS_VIEW_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$RELATIONS V',
    'WHERE V.RDB$RELATION_NAME = :RELATION_NAME');

  SQL_INIT_VIEW: array[0..6] of string = (
    'SELECT',
    '  R.RDB$OWNER_NAME AS OWNER_NAME,',
    '  R.RDB$DESCRIPTION AS DESCRIPTION,',
    '  R.RDB$VIEW_SOURCE AS SOURCE',
    'FROM RDB$RELATIONS R',
    'WHERE R.RDB$RELATION_NAME = :RELATION_NAME AND',
    '      R.RDB$VIEW_SOURCE IS NOT NULL');

  SQL_INIT_VIEW_FIELDS: array[0..5] of string = (
    'SELECT',
    '  FF.RDB$FIELD_NAME AS FIELD_NAME,',
    '  FF.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$RELATION_FIELDS FF',
    'WHERE FF.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY FF.RDB$FIELD_POSITION');

  SQL_GET_VIEW_FIELDS: array[0..4] of string = (
    'SELECT',
    '  FF.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$RELATION_FIELDS FF',
    'WHERE FF.RDB$RELATION_NAME = :RELATION_NAME',
    'ORDER BY FF.RDB$FIELD_POSITION');

  SQL_GET_COMMENT_VIEW: array[0..3] of string = (
    'SELECT',
    '  R.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$RELATIONS R',
    'WHERE R.RDB$RELATION_NAME = ''%s'';');

  SQL_SET_COMMENT_VIEW: array[0..2] of string = (
    'UPDATE RDB$RELATIONS R SET R.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE R.RDB$RELATION_NAME = ''%s'';');

  SQL_SET_COMMENT_VIEW_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$RELATIONS R',
    'SET R.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE R.RDB$RELATION_NAME = ''%s'';');

   SQL_VIEWS_DEPENDENCIES:string=
' SELECT'#$D#$A+
'   V.RDB$VIEW_NAME AS VIEW_NAME,'#$D#$A+
'   V.RDB$RELATION_NAME AS USED_VIEW'#$D#$A+
' FROM    RDB$VIEW_RELATIONS V'#$D#$A+
'   JOIN  RDB$RELATIONS R ON R.RDB$RELATION_NAME = V.RDB$RELATION_NAME'#$D#$A+
' WHERE'#$D#$A+
'  NOT R.RDB$VIEW_BLR IS NULL'#$D#$A+
'UNION'#$D#$A+
'    SELECT'#$D#$A+
'      RF.RDB$RELATION_NAME AS VIEW_NAME,'#$D#$A+
'      D.RDB$DEPENDED_ON_NAME AS USED_VIEW'#$D#$A+
''#$D#$A+
'    FROM RDB$DEPENDENCIES D'#$D#$A+
'      JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#$D#$A+
'      JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME'#$D#$A+
'      JOIN RDB$RELATIONS R1 ON R1.RDB$RELATION_NAME||''''= D.RDB$DEPENDED_ON_NAME'#$D#$A+
'    WHERE NOT R.RDB$VIEW_BLR IS NULL AND'#$D#$A+
'          NOT R1.RDB$VIEW_BLR IS NULL AND'#$D#$A+
'          D.RDB$DEPENDENT_TYPE = 3';

{     'select distinct d1.rdb$dependent_name, v1.rdb$view_name '#13#10 +
     'from rdb$dependencies d1, rdb$view_relations v1'#13#10 +
     'where (d1.rdb$dependent_type = 1) and'#13#10 +
     '(d1.rdb$depended_on_name = v1.rdb$view_name )' ;
 }
   SQL_VIEWS_USED_BY:string=
'     SELECT DISTINCT D1.RDB$DEPENDENT_NAME '#13#10 +
'     FROM RDB$DEPENDENCIES D1, RDB$VIEW_RELATIONS V1'#13#10 +
'     WHERE (D1.RDB$DEPENDENT_TYPE = 1) AND'#13#10 +
'     (D1.RDB$DEPENDED_ON_NAME = V1.RDB$VIEW_NAME )'#13#10 +
'     AND V1.RDB$VIEW_NAME =:VIEW_NAME'#13#10 +
'     UNION'#13#10 +
'     SELECT   DISTINCT'#13#10 +
'      RF.RDB$RELATION_NAME AS OBJECT_NAME'#13#10 +
'     FROM RDB$DEPENDENCIES D'#13#10 +
'      JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#13#10 +
'      JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME'#13#10 +
'     WHERE NOT R.RDB$VIEW_BLR IS NULL AND'#13#10 +
'          D.RDB$DEPENDENT_TYPE = 3 AND'#13#10 +
'          D.RDB$DEPENDED_ON_NAME = :VIEW_NAME' ;


// -> Procedure ----------------------------------------------------------------
  SQL_GET_PROCEDURE_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  P.RDB$PROCEDURE_NAME AS NAME',
    'FROM RDB$PROCEDURES P',
    'WHERE P.RDB$SYSTEM_FLAG IS NULL OR P.RDB$SYSTEM_FLAG <> 1');

  SQL_GET_PROCEDURES_WITH_COMMENTS:string=
    'SELECT '#13#10+
    '  P.RDB$PROCEDURE_NAME AS NAME'#13#10+
    'FROM RDB$PROCEDURES P'#13#10+
    'WHERE P.RDB$SYSTEM_FLAG IS NULL OR P.RDB$SYSTEM_FLAG <> 1'#13#10+
    'AND NOT P.RDB$DESCRIPTION IS NULL'#13#10+
    'UNION'#13#10+
    'SELECT  PP.RDB$PROCEDURE_NAME'#13#10+
    'FROM RDB$PROCEDURE_PARAMETERS PP'#13#10+
    'WHERE NOT PP.RDB$DESCRIPTION IS NULL'
    ;

  SQL_EXISTS_PROCEDURE_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$PROCEDURES P',
    'WHERE P.RDB$PROCEDURE_NAME = :PROCEDURE_NAME');

  SQL_INIT_PROCEDURE: array[0..5] of string = (
    'SELECT',
    '  PR.RDB$OWNER_NAME AS OWNER_NAME,',
    '  PR.RDB$DESCRIPTION AS DESCRIPTION,',
    '  PR.RDB$PROCEDURE_SOURCE AS SOURCE',
    'FROM RDB$PROCEDURES PR',
    'WHERE PR.RDB$PROCEDURE_NAME = :PROCEDURE_NAME');

  SQL_INIT_PROCEDURE_PARAMS1: array[0..18] of string = (
    'SELECT',
    '  PP.RDB$PARAMETER_NAME AS PARAMETER_NAME,',
    '  PP.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  0 AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.rdb$default_source AS DEFAULT_SOURCE ',
    'FROM RDB$PROCEDURE_PARAMETERS PP',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = PP.RDB$FIELD_SOURCE',
    'WHERE PP.RDB$PROCEDURE_NAME = :PROCEDURE_NAME AND',
    '      PP.RDB$PARAMETER_TYPE = :PARAMETER_TYPE',
    'ORDER BY PP.RDB$PARAMETER_NUMBER');

  SQL_INIT_PROCEDURE_PARAMS3: array[0..18] of string = (
    'SELECT',
    '  PP.RDB$PARAMETER_NAME AS PARAMETER_NAME,',
    '  PP.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.rdb$default_source AS DEFAULT_SOURCE ',
    'FROM RDB$PROCEDURE_PARAMETERS PP',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = PP.RDB$FIELD_SOURCE',
    'WHERE PP.RDB$PROCEDURE_NAME = :PROCEDURE_NAME AND',
    '      PP.RDB$PARAMETER_TYPE = :PARAMETER_TYPE',
    'ORDER BY PP.RDB$PARAMETER_NUMBER');

  SQL_INIT_PROCEDURE_PARAMS4: array[0..21] of string = (
    'SELECT',
    '  PP.RDB$PARAMETER_NAME AS PARAMETER_NAME,',
    '  PP.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.rdb$default_source AS DEFAULT_SOURCE ',

    '  , PP.rdb$default_source AS DEFAULT_SOURCE_OVER',
    '  , PP.rdb$parameter_mechanism AS MECHANIZM',
    ' , pp.rdb$field_source AS F_BASED_ON_DOMAIN',


    'FROM RDB$PROCEDURE_PARAMETERS PP',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = PP.RDB$FIELD_SOURCE',
    'WHERE PP.RDB$PROCEDURE_NAME = :PROCEDURE_NAME AND',
    '      PP.RDB$PARAMETER_TYPE = :PARAMETER_TYPE',
    'ORDER BY PP.RDB$PARAMETER_NUMBER');


  SQL_GET_PROCEDURE_PARAMS: array[0..5] of string = (
    'SELECT',
    '  PP.RDB$PARAMETER_NAME AS PARAMETER_NAME',
    'FROM RDB$PROCEDURE_PARAMETERS PP',
    'WHERE PP.RDB$PROCEDURE_NAME = :PROCEDURE_NAME AND',
    '      PP.RDB$PARAMETER_TYPE = 1',
    'ORDER BY PP.RDB$PARAMETER_NUMBER');

  SQL_GET_OUT_PROCEDURE_PARAMS1: array[0..14] of string = (
    'SELECT',
    '  PP.RDB$PARAMETER_NAME AS PARAMETER_NAME,',
//    '  PP.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  0 AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID',
    'FROM RDB$PROCEDURE_PARAMETERS PP',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = PP.RDB$FIELD_SOURCE',
    'WHERE PP.RDB$PROCEDURE_NAME = :PROCEDURE_NAME AND',
    '      PP.RDB$PARAMETER_TYPE = 1',
    'ORDER BY PP.RDB$PARAMETER_NUMBER');

  SQL_GET_OUT_PROCEDURE_PARAMS3: array[0..14] of string = (
    'SELECT',
    '  PP.RDB$PARAMETER_NAME AS PARAMETER_NAME,',
//    '  PP.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID',
    'FROM RDB$PROCEDURE_PARAMETERS PP',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = PP.RDB$FIELD_SOURCE',
    'WHERE PP.RDB$PROCEDURE_NAME = :PROCEDURE_NAME AND',
    '      PP.RDB$PARAMETER_TYPE = 1',
    'ORDER BY PP.RDB$PARAMETER_NUMBER');

  SQL_GET_PROCEDURE_PARAMS1: array[0..14] of string = (
    'SELECT',
    '  PP.RDB$PARAMETER_NAME AS PARAMETER_NAME,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  0 AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID',
    'FROM RDB$PROCEDURE_PARAMETERS PP',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = PP.RDB$FIELD_SOURCE',
    'WHERE PP.RDB$PROCEDURE_NAME = :PROCEDURE_NAME AND',
    '      PP.RDB$PARAMETER_TYPE = :PARAMETER_TYPE',
    'ORDER BY PP.RDB$PARAMETER_NUMBER');

  SQL_GET_PROCEDURE_PARAMS3: array[0..14] of string = (
    'SELECT',
    '  PP.RDB$PARAMETER_NAME AS PARAMETER_NAME,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID',
    'FROM RDB$PROCEDURE_PARAMETERS PP',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = PP.RDB$FIELD_SOURCE',
    'WHERE PP.RDB$PROCEDURE_NAME = :PROCEDURE_NAME AND',
    '      PP.RDB$PARAMETER_TYPE = :PARAMETER_TYPE',
    'ORDER BY PP.RDB$PARAMETER_NUMBER');

  SQL_GET_COMMENT_PROCEDURE: array[0..3] of string = (
    'SELECT',
    '  P.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$PROCEDURES P',
    'WHERE P.RDB$PROCEDURE_NAME = ''%s'';');

  SQL_SET_COMMENT_PROCEDURE: array[0..2] of string = (
    'UPDATE RDB$PROCEDURES P SET P.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE P.RDB$PROCEDURE_NAME = ''%s'';');

  SQL_SET_COMMENT_PROCEDURE_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$PROCEDURES P',
    'SET P.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE P.RDB$PROCEDURE_NAME = ''%s'';');

// -> Trigger ------------------------------------------------------------------
{  SQL_GET_TRIGGER_NAME_LIST: array[0..7] of string = (
    'SELECT',
    '  T.RDB$TRIGGER_NAME AS NAME',
    'FROM RDB$TRIGGERS T',
    'LEFT  JOIN RDB$RELATIONS R ON T.RDB$RELATION_NAME = R.RDB$RELATION_NAME',
    'WHERE (R.RDB$SYSTEM_FLAG IS NULL OR R.RDB$SYSTEM_FLAG <> 1) AND',
    '       NOT EXISTS (SELECT *',
    '                   FROM RDB$CHECK_CONSTRAINTS CHK',
    '                   WHERE T.RDB$TRIGGER_NAME = CHK.RDB$TRIGGER_NAME)');


}

  SQL_GET_TRIGGER_NAME_LIST: array[0..0] of string = (
'    SELECT'#$D#$A+
'      T.RDB$TRIGGER_NAME AS NAME, 0'#$D#$A+
'    FROM RDB$TRIGGERS T'#$D#$A+
'     JOIN RDB$RELATIONS R ON T.RDB$RELATION_NAME = R.RDB$RELATION_NAME'#$D#$A+
'    WHERE (R.rdb$view_blr IS NULL) and (R.RDB$SYSTEM_FLAG IS NULL OR R.RDB$SYSTEM_FLAG <> 1)'#$D#$A+
'    AND       NOT EXISTS (SELECT *'#$D#$A+
'                       FROM RDB$CHECK_CONSTRAINTS CHK'#$D#$A+
'                       WHERE T.RDB$TRIGGER_NAME = CHK.RDB$TRIGGER_NAME)'#$D#$A+
''#$D#$A+
'    union all'#$D#$A+
'    SELECT'#$D#$A+
'      T.RDB$TRIGGER_NAME AS NAME, 1'#$D#$A+
'    FROM RDB$TRIGGERS T'#$D#$A+
'     JOIN RDB$RELATIONS R ON T.RDB$RELATION_NAME = R.RDB$RELATION_NAME'#$D#$A+
'    WHERE (R.rdb$view_blr IS NOT NULL) and (R.RDB$SYSTEM_FLAG IS NULL OR R.RDB$SYSTEM_FLAG <> 1)'#$D#$A+
''#$D#$A+
'    union all'#$D#$A+
'    SELECT'#$D#$A+
'      T.RDB$TRIGGER_NAME AS NAME, 3'#$D#$A+
'    FROM RDB$TRIGGERS T'#$D#$A+
'    LEFT  JOIN RDB$RELATIONS R ON T.RDB$RELATION_NAME = R.RDB$RELATION_NAME'#$D#$A+
'    WHERE (R.rdb$relation_id IS NULL) and (R.RDB$SYSTEM_FLAG IS NULL OR R.RDB$SYSTEM_FLAG <> 1)'
);

  SQL_GET_TRIGGERS_WITH_COMMENTS=
    'SELECT  T.RDB$TRIGGER_NAME AS NAME '#13#10+
    'FROM RDB$TRIGGERS T '#13#10+
    '  JOIN RDB$RELATIONS R ON T.RDB$RELATION_NAME = R.RDB$RELATION_NAME'#13#10+
    'WHERE (R.RDB$SYSTEM_FLAG IS NULL OR R.RDB$SYSTEM_FLAG <> 1) AND'#13#10+
    'NOT T.RDB$DESCRIPTION IS NULL AND '#13#10+
    '       NOT EXISTS (SELECT *'#13#10+
    '                   FROM RDB$CHECK_CONSTRAINTS CHK'#13#10+
    '                   WHERE T.RDB$TRIGGER_NAME = CHK.RDB$TRIGGER_NAME)';



  SQL_EXISTS_TRIGGER_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$TRIGGERS TR',
    'WHERE TR.RDB$TRIGGER_NAME = :TRIGGER_NAME');

  SQL_INIT_TRIGGER: array[0..8] of string = (
    'SELECT',
    '  TR.RDB$DESCRIPTION AS DESCRIPTION,',
    '  TR.RDB$TRIGGER_SOURCE AS SOURCE,',
    '  TR.RDB$RELATION_NAME AS TABLE_NAME,',
    '  TR.RDB$TRIGGER_SEQUENCE AS POSITION1,',
    '  TR.RDB$TRIGGER_TYPE AS TRIGGER_TYPE_ID,',
    '  TR.RDB$TRIGGER_INACTIVE AS IN_ACTIVE',
    'FROM RDB$TRIGGERS TR',
    'WHERE TR.RDB$TRIGGER_NAME = :TRIGGER_NAME');

  SQL_GET_COMMENT_TRIGGER: array[0..3] of string = (
    'SELECT',
    '  T.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$TRIGGERS T',
    'WHERE T.RDB$TRIGGER_NAME = ''%s'';');

  SQL_SET_COMMENT_TRIGGER: array[0..2] of string = (
    'UPDATE RDB$TRIGGERS T SET T.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE T.RDB$TRIGGER_NAME = ''%s'';');

  SQL_SET_COMMENT_TRIGGER_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$TRIGGERS T',
    'SET T.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE T.RDB$TRIGGER_NAME = ''%s'';');

// -> Generator ----------------------------------------------------------------
  SQL_GET_GENERATOR_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  G.RDB$GENERATOR_NAME AS NAME',
    'FROM RDB$GENERATORS G',
    'WHERE (G.RDB$SYSTEM_FLAG IS NULL) OR (G.RDB$SYSTEM_FLAG <> 1)');

  SQL_EXISTS_GENERATOR_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$GENERATORS G',
    'WHERE G.RDB$GENERATOR_NAME = :GENERATOR_NAME');

  SQL_INIT_GENERATOR: array[0..0] of string = (
    'SELECT GEN_ID(%s, 0) FROM RDB$DATABASE');

// -> Exception ----------------------------------------------------------------
  SQL_GET_EXCEPTION_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  E.RDB$EXCEPTION_NAME AS NAME',
    'FROM RDB$EXCEPTIONS E',
    'WHERE (E.RDB$SYSTEM_FLAG IS NULL) OR (E.RDB$SYSTEM_FLAG <> 1)');

  SQL_GET_EXCEPTIONS_WITH_COMMENTS=
    'SELECT'#13#10+
    '  E.RDB$EXCEPTION_NAME AS NAME'#13#10+
    'FROM RDB$EXCEPTIONS E'#13#10+
    'WHERE (E.RDB$SYSTEM_FLAG IS NULL) OR (E.RDB$SYSTEM_FLAG <> 1)'#13#10+
    'AND NOT E.RDB$DESCRIPTION IS NULL'
    ;

  SQL_EXISTS_EXCEPTION_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$EXCEPTIONS E',
    'WHERE E.RDB$EXCEPTION_NAME = :EXCEPTION_NAME');

  SQL_INIT_EXCEPTION: array[0..5] of string = (
    'SELECT',
    '  E.RDB$MESSAGE || '''' AS TEXT,',
    '  E.RDB$EXCEPTION_NUMBER AS NUMBER_,',
    '  E.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$EXCEPTIONS E',
    'WHERE E.RDB$EXCEPTION_NAME = :EXCEPTION_NAME');

  SQL_GET_COMMENT_EXCEPTION: array[0..3] of string = (
    'SELECT',
    '  E.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$EXCEPTIONS E',
    'WHERE E.RDB$EXCEPTION_NAME = ''%s'';');

  SQL_SET_COMMENT_EXCEPTION: array[0..2] of string = (
    'UPDATE RDB$EXCEPTIONS E SET E.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE E.RDB$EXCEPTION_NAME = ''%s'';');

  SQL_SET_COMMENT_EXCEPTION_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$EXCEPTIONS E',
    'SET E.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE E.RDB$EXCEPTION_NAME = ''%s'';');

// -> Function -----------------------------------------------------------------
  SQL_GET_FUNCTION_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  F.RDB$FUNCTION_NAME AS NAME',
    'FROM RDB$FUNCTIONS F',
    'WHERE (F.RDB$SYSTEM_FLAG IS NULL) OR (F.RDB$SYSTEM_FLAG <> 1)');

  SQL_GET_FUNCTIONS_WITH_COMMENTS=
    'SELECT'#13#10+
    '  F.RDB$FUNCTION_NAME AS NAME'#13#10+
    'FROM RDB$FUNCTIONS F'#13#10+
    'WHERE (F.RDB$SYSTEM_FLAG IS NULL) OR (F.RDB$SYSTEM_FLAG <> 1)'#13#10+
    'AND NOT F.RDB$DESCRIPTION IS NULL'
    ;


  SQL_EXISTS_FUNCTION_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$FUNCTIONS F',
    'WHERE F.RDB$FUNCTION_NAME = :FUNCTION_NAME');

  SQL_INIT_FUNCTION: array[0..6] of string = (
    'SELECT',
    '  F.RDB$RETURN_ARGUMENT AS RETURN_ARGUMENT,',
    '  F.RDB$ENTRYPOINT AS ENTRYPOINT,',
    '  F.RDB$MODULE_NAME AS MODULENAME,',
    '  F.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$FUNCTIONS F',
    'WHERE F.RDB$FUNCTION_NAME = :FUNCTION_NAME');

  SQL_INIT_FUNCTION_ARGUMENTS1: array[0..9] of string = (
    'SELECT',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$FIELD_LENGTH AS LENGTH_,',
//    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  0 AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$MECHANISM AS MECHANISM',
    'FROM RDB$FUNCTION_ARGUMENTS F',
    'WHERE F.RDB$FUNCTION_NAME = :FUNCTION_NAME',
    'ORDER BY F.RDB$ARGUMENT_POSITION');

  SQL_INIT_FUNCTION_ARGUMENTS3: array[0..9] of string = (
    'SELECT',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$FIELD_LENGTH AS LENGTH_,',
//    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$MECHANISM AS MECHANISM',
    'FROM RDB$FUNCTION_ARGUMENTS F',
    'WHERE F.RDB$FUNCTION_NAME = :FUNCTION_NAME',
    'ORDER BY F.RDB$ARGUMENT_POSITION');

  SQL_GET_COMMENT_FUNCTION: array[0..3] of string = (
    'SELECT',
    '  F.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$FUNCTIONS F',
    'WHERE F.RDB$FUNCTION_NAME = ''%s'';');

  SQL_SET_COMMENT_FUNCTION: array[0..2] of string = (
    'UPDATE RDB$FUNCTIONS F SET F.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE F.RDB$FUNCTION_NAME = ''%s'';');

  SQL_SET_COMMENT_FUNCTION_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$FUNCTIONS F',
    'SET F.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE F.RDB$FUNCTION_NAME = ''%s'';');

// -> Filter -------------------------------------------------------------------
  SQL_GET_FILTER_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  F.RDB$FUNCTION_NAME AS NAME',
    'FROM RDB$FILTERS F',
    'WHERE (F.RDB$SYSTEM_FLAG IS NULL) OR (F.RDB$SYSTEM_FLAG <> 1)');

  SQL_EXISTS_FILTER_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$FILTERS F',
    'WHERE F.RDB$FUNCTION_NAME = :FUNCTION_NAME');

  SQL_INIT_FILTER: array[0..7] of string = (
    'SELECT',
    '  F.RDB$INPUT_SUB_TYPE AS INPUT_SUB_TYPE,',
    '  F.RDB$OUTPUT_SUB_TYPE AS OUTPUT_SUB_TYPE,',
    '  F.RDB$ENTRYPOINT AS ENTRYPOINT,',
    '  F.RDB$MODULE_NAME AS MODULENAME,',
    '  F.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$FILTERS F',
    'WHERE F.RDB$FUNCTION_NAME = :FUNCTION_NAME');

  SQL_GET_COMMENT_FILTER: array[0..3] of string = (
    'SELECT',
    '  F.RDB$DESCRIPTION AS DESCRIPTION',
    'FROM RDB$FILTERS F',
    'WHERE F.RDB$FUNCTION_NAME = ''%s'';');

  SQL_SET_COMMENT_FILTER: array[0..2] of string = (
    'UPDATE RDB$FILTERS F SET F.RDB$DESCRIPTION =',
    '''%s''',
    'WHERE F.RDB$FUNCTION_NAME = ''%s'';');

  SQL_SET_COMMENT_FILTER_AS_PARAM: array[0..2] of string = (
    'UPDATE RDB$FILTERS F',
    'SET F.RDB$DESCRIPTION = :DESCRIPTION',
    'WHERE F.RDB$FUNCTION_NAME = ''%s'';');

// -> Role ---------------------------------------------------------------------
  SQL_GET_ROLE_NAME_LIST: array[0..2] of string = (
    'SELECT',
    '  R.RDB$ROLE_NAME AS NAME',
    'FROM RDB$ROLES R');
//    'WHERE (R.RDB$SYSTEM_FLAG IS NULL) OR (R.RDB$SYSTEM_FLAG <> 1)');

  SQL_EXISTS_ROLE_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$ROLES R',
    'WHERE R.RDB$ROLE_NAME = :ROLE_NAME');

  SQL_INIT_ROLE: array[0..3] of string = (
    'SELECT',
    '  R.RDB$OWNER_NAME AS OWNER_NAME',
    'FROM RDB$ROLES R',
    'WHERE R.RDB$ROLE_NAME = :ROLE_NAME');

// -> Shadow -------------------------------------------------------------------
  SQL_GET_SHADOW_NAME_LIST: array[0..3] of string = (
    'SELECT',
    '  F.RDB$SHADOW_NUMBER AS NAME',
    'FROM RDB$FILES F',
    'WHERE (F.RDB$SHADOW_NUMBER > 0) AND (F.RDB$FILE_SEQUENCE = 0)');

  SQL_EXISTS_SHADOW_NAME: array[0..2] of string = (
    'SELECT 1',
    'FROM RDB$FILES F',
    'WHERE F.RDB$SHADOW_NUMBER = :SHADOW_NUMBER');

  SQL_INIT_SHADOW: array[0..5] of string = (
    'SELECT',
    '  F.RDB$FILE_NAME AS FILE_NAME,',
    '  F.RDB$FILE_LENGTH AS FILE_LENGTH,',
    '  F.RDB$FILE_FLAGS AS FILE_FLAGS',
    'FROM RDB$FILES F',
    'WHERE (F.RDB$SHADOW_NUMBER = :SHADOW_NUMBER) AND F.RDB$FILE_SEQUENCE = 0');


{*******************************************************************************
 D E P E N D E N C I E S  #  D E P E N D E N C I E S  #  D E P E N D E N C I E S
*******************************************************************************}

// D O M A I N S

  SQL_GET_DOMAIN_USED_BY: array[0..0] of string = (
    'SELECT'#13#10+
    '  0 AS DEPENDENT_TYPE,'#13#10+
    '  F.RDB$RELATION_NAME AS OBJECT_NAME,'#13#10+
    '  F.RDB$FIELD_NAME AS FIELD_NAME'#13#10+
    'FROM RDB$RELATION_FIELDS F'#13#10+
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = F.RDB$RELATION_NAME'#13#10+
    'WHERE R.RDB$VIEW_BLR IS NULL AND F.RDB$FIELD_SOURCE = :OBJECT'#13#10+
    'UNION ALL'#13#10+
    'SELECT'#13#10+
    '  1 AS DEPENDENT_TYPE,'#13#10+
    '  F.RDB$RELATION_NAME AS OBJECT_NAME,'#13#10+
    '  F.RDB$FIELD_NAME AS FIELD_NAME'#13#10+
    'FROM RDB$RELATION_FIELDS F'#13#10+
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = F.RDB$RELATION_NAME'#13#10+
    'WHERE R.RDB$VIEW_BLR IS NOT NULL AND F.RDB$FIELD_SOURCE = :OBJECT'#13#10+
    'UNION ALL'#13#10+
    'SELECT'#13#10+
    '  5 AS DEPENDENT_TYPE,'#13#10+
    '  PP.rdb$procedure_name AS OBJECT_NAME,'#13#10+
    '  PP.rdb$parameter_name AS FIELD_NAME'#13#10+
    'FROM rdb$procedure_parameters PP'#13#10+
    'WHERE PP.rdb$field_source=:OBJECT'#13#10+

    'UNION ALL'#13#10+
    'SELECT'#13#10+
    ' DD.rdb$dependent_type DEPENDENT_TYPE,'#13#10+
    ' DD.rdb$dependent_name AS OBJECT_NAME,'#13#10+
    ' DD.rdb$field_name AS FIELD_NAME'#13#10+
    'FROM rdb$dependencies DD'#13#10+
    'WHERE DD.rdb$depended_on_name=:OBJECT'#13#10+
    'and DD.rdb$dependent_type=5'#13#10+

    'UNION ALL'#13#10+
    'SELECT'#13#10+
    '  DD.rdb$dependent_type DEPENDENT_TYPE,'#13#10+
    '  DD.rdb$dependent_name AS OBJECT_NAME,'#13#10+
    '  DD.rdb$field_name AS FIELD_NAME'#13#10+
    'FROM rdb$dependencies DD'#13#10+
    'WHERE DD.rdb$depended_on_name=:OBJECT'#13#10+
    'and DD.rdb$dependent_type=2'

    );

// T A B L E S

  SQL_GET_TABLE_USED_BY: array[0..65] of string = (
    'SELECT',
    '  D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDENT_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDED_ON_TYPE = 0 AND',
    '      D.RDB$DEPENDENT_TYPE <> 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  RF.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME',
    'WHERE R.RDB$VIEW_BLR IS NULL AND',
    '      D.RDB$DEPENDENT_TYPE = 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RC1.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  INS2.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC1,',
    '     RDB$RELATION_CONSTRAINTS RC2,',
    '     RDB$INDEX_SEGMENTS INS1,',
    '     RDB$INDEX_SEGMENTS INS2,',
    '     RDB$REF_CONSTRAINTS C',
    'WHERE RC1.RDB$CONSTRAINT_TYPE = ''FOREIGN KEY'' AND',
    '      RC1.RDB$CONSTRAINT_NAME = C.RDB$CONSTRAINT_NAME AND',
    '      C.RDB$CONST_NAME_UQ = RC2.RDB$CONSTRAINT_NAME AND',
    '      RC2.RDB$INDEX_NAME = INS1.RDB$INDEX_NAME AND',
    '      RC1.RDB$INDEX_NAME = INS2.RDB$INDEX_NAME AND',
    '      RC2.RDB$RELATION_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(4 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RC.RDB$CONSTRAINT_NAME AS OBJECT_NAME,',
    '  INS.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    '  LEFT JOIN RDB$INDEX_SEGMENTS INS ON INS.RDB$INDEX_NAME = RC.RDB$INDEX_NAME',
    'WHERE (RC.RDB$CONSTRAINT_TYPE = ''PRIMARY KEY'' OR',
    '       RC.RDB$CONSTRAINT_TYPE = ''UNIQUE'' OR',
    '       RC.RDB$CONSTRAINT_TYPE = ''FOREIGN KEY'' OR',
    '       RC.RDB$CONSTRAINT_TYPE = ''CHECK'') AND RC.RDB$RELATION_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(10 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  IDX.RDB$INDEX_NAME AS OBJECT_NAME,',
    '  IDXS.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$INDICES IDX',
    '  JOIN RDB$INDEX_SEGMENTS IDXS ON IDXS.RDB$INDEX_NAME = IDX.RDB$INDEX_NAME',
    'WHERE IDX.RDB$RELATION_NAME = :OBJECT AND ',
    '      NOT IDX.RDB$INDEX_NAME STARTING WITH ''RDB$'' AND',
    '      NOT EXISTS (SELECT 1',
    '                  FROM RDB$RELATION_CONSTRAINTS RC3',
    '                  WHERE RC3.RDB$INDEX_NAME = IDX.RDB$INDEX_NAME)');

  SQL_GET_TABLE_USES: array[0..36] of string = (
  'SELECT DISTINCT'#13#10+
  'CAST(9 AS SMALLINT) AS DEPENDENT_TYPE,'#13#10+
  '  F.RDB$FIELD_SOURCE AS OBJECT_NAME,'#13#10+
  'CAST(NULL AS VARCHAR(167)) AS FIELD_NAME'#13#10+
  'FROM RDB$RELATION_FIELDS F'#13#10+
  '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = F.RDB$RELATION_NAME'#13#10+
  'WHERE  F.RDB$RELATION_NAME  = :OBJECT     AND  NOT F.RDB$FIELD_SOURCE LIKE ''RDB$%'''#13#10+
  'UNION ALL',

    'SELECT',
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,',
    ' CAST(D.RDB$FIELD_NAME AS VARCHAR(167)) AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDENT_TYPE = 0 AND',
    '      D.RDB$DEPENDENT_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,',
    '  CAST(D.RDB$FIELD_NAME AS VARCHAR(167)) AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    'WHERE D.RDB$DEPENDENT_TYPE = 3 AND',
    '      RF.RDB$RELATION_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RC2.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  CAST(INS1.RDB$FIELD_NAME AS VARCHAR(167)) AS FIELD_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC1,',
    '     RDB$RELATION_CONSTRAINTS RC2,',
    '     RDB$INDEX_SEGMENTS INS1,',
    '     RDB$INDEX_SEGMENTS INS2,',
    '     RDB$REF_CONSTRAINTS C',
    'WHERE RC1.RDB$CONSTRAINT_TYPE = ''FOREIGN KEY'' AND',
    '      RC1.RDB$CONSTRAINT_NAME = C.RDB$CONSTRAINT_NAME AND',
    '      C.RDB$CONST_NAME_UQ = RC2.RDB$CONSTRAINT_NAME AND',
    '      RC2.RDB$INDEX_NAME = INS1.RDB$INDEX_NAME AND',
    '      RC1.RDB$INDEX_NAME = INS2.RDB$INDEX_NAME AND',
    '      RC1.RDB$RELATION_NAME = :OBJECT');

// F I E L D S

  SQL_GET_FIELD_USED_BY: array[0..51] of string = (
    'SELECT',
    '  D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDENT_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDENT_TYPE <> 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = ''%s'' AND',
    '      D.RDB$FIELD_NAME = ''%s''',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  RF.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME',
    'WHERE R.RDB$VIEW_BLR IS NULL AND',
    '      D.RDB$DEPENDENT_TYPE = 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = ''%s'' AND',
    '      D.RDB$FIELD_NAME = ''%s''',

    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(4 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RC.RDB$CONSTRAINT_NAME AS OBJECT_NAME,',
    '  INS.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$RELATION_CONSTRAINTS RC',
    '  LEFT JOIN RDB$INDEX_SEGMENTS INS ON INS.RDB$INDEX_NAME = RC.RDB$INDEX_NAME',
    'WHERE (RC.RDB$CONSTRAINT_TYPE = ''PRIMARY KEY'' OR',
    '       RC.RDB$CONSTRAINT_TYPE = ''UNIQUE'' OR',
    '       RC.RDB$CONSTRAINT_TYPE = ''FOREIGN KEY'' OR',
    '       RC.RDB$CONSTRAINT_TYPE = ''CHECK'') AND',
    '      RC.RDB$RELATION_NAME = ''%s'' AND',
    '      INS.RDB$FIELD_NAME = ''%s''',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(10 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  IDX.RDB$INDEX_NAME AS OBJECT_NAME,',
    '  IDXS.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$INDICES IDX',
    '  JOIN RDB$INDEX_SEGMENTS IDXS ON IDXS.RDB$INDEX_NAME = IDX.RDB$INDEX_NAME',
    'WHERE IDX.RDB$RELATION_NAME = ''%s'' AND ',
    '      IDXS.RDB$FIELD_NAME = ''%s'' AND',
    '      NOT IDX.RDB$INDEX_NAME STARTING WITH ''RDB$'' AND',
    '      NOT EXISTS (SELECT 1',
    '                  FROM RDB$RELATION_CONSTRAINTS RC3',
    '                  WHERE RC3.RDB$INDEX_NAME = IDX.RDB$INDEX_NAME)');




  {
  SQL_CHECK_FIELD_IS_NULL: array[0..6] of string = (
    'SELECT',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  RF.RDB$NULL_FLAG AS F_NOT_NULL',
    'FROM RDB$RELATION_FIELDS RF',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE',
    'WHERE RF.RDB$RELATION_NAME = :RELATION_NAME AND',
    '      RF.RDB$FIELD_NAME = :FIELD_NAME');
  }



 SQL_GET_FIELD_USES:  string =
  'SELECT'#13#10+
  'CAST(9 AS SMALLINT) AS DEPENDENT_TYPE,'#13#10+
  '  F.RDB$FIELD_SOURCE AS OBJECT_NAME,'#13#10+
  'CAST(NULL AS VARCHAR(160)) AS FIELD_NAME'#13#10+
  'FROM RDB$RELATION_FIELDS F'#13#10+
  '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = F.RDB$RELATION_NAME'#13#10+
  'WHERE  F.RDB$RELATION_NAME  = ''%s''     AND  NOT F.RDB$FIELD_SOURCE STARTING ''RDB$'''#13#10+
  '   AND F.RDB$FIELD_NAME     = ''%s'''#13#10
  +
  'UNION ALL'#13#10+

    'SELECT'#13#10+
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,'#13#10+
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,'#13#10+
    'CAST(D.RDB$FIELD_NAME AS VARCHAR(160))AS FIELD_NAME'#13#10+
    'FROM RDB$DEPENDENCIES D'#13#10+
    'WHERE D.RDB$DEPENDENT_TYPE = 0 AND'#13#10+
    '      D.RDB$DEPENDENT_NAME = ''%s'' AND'#13#10+
    '      D.RDB$FIELD_NAME     = ''%s'''#13#10+
    ' '#13#10+
    'UNION ALL'#13#10+
    ' '#13#10+
    'SELECT'#13#10+
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,'#13#10+
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,'#13#10+
    '  CAST(D.RDB$FIELD_NAME AS VARCHAR(160)) AS FIELD_NAME'#13#10+
    'FROM RDB$DEPENDENCIES D'#13#10+
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#13#10+
    'WHERE D.RDB$DEPENDENT_TYPE = 3 AND'#13#10+
    '      RF.RDB$RELATION_NAME = ''%s'''#13#10+
    '      AND D.RDB$FIELD_NAME = ''%s'''#13#10+
    ' '#13#10+
    'UNION ALL'#13#10+
    ' '#13#10+
    'SELECT'#13#10+
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,'#13#10+
    '  RC2.RDB$RELATION_NAME AS OBJECT_NAME,'#13#10+
    '  CAST(INS1.RDB$FIELD_NAME AS VARCHAR(160)) AS FIELD_NAME'#13#10+
    'FROM RDB$RELATION_CONSTRAINTS RC1,'#13#10+
    '     RDB$RELATION_CONSTRAINTS RC2,'#13#10+
    '     RDB$INDEX_SEGMENTS INS1,'#13#10+
    '     RDB$INDEX_SEGMENTS INS2,'#13#10+
    '     RDB$REF_CONSTRAINTS C'#13#10+
    'WHERE RC1.RDB$CONSTRAINT_TYPE = ''FOREIGN KEY'' AND'#13#10+
    '      RC1.RDB$CONSTRAINT_NAME = C.RDB$CONSTRAINT_NAME AND'#13#10+
    '      C.RDB$CONST_NAME_UQ = RC2.RDB$CONSTRAINT_NAME AND'#13#10+
    '      RC2.RDB$INDEX_NAME = INS1.RDB$INDEX_NAME AND'#13#10+
    '      RC1.RDB$INDEX_NAME = INS2.RDB$INDEX_NAME AND'#13#10+
    '      RC1.RDB$RELATION_NAME = ''%s'''#13#10+
    '      AND INS1.RDB$FIELD_NAME     = ''%s'''
    
    ;

// V I E W S
// Используется ТОЛЬКО для Recreate  DDL
  SQL_GET_VIEW_USED_BY1:string =
'    SELECT'#$D#$A+
'      D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,'#$D#$A+
'      D.RDB$DEPENDENT_NAME AS OBJECT_NAME'#$D#$A+
'    FROM RDB$DEPENDENCIES D'#$D#$A+
'    WHERE D.RDB$DEPENDED_ON_TYPE IN (0,1) AND'#$D#$A+
'          D.RDB$DEPENDENT_TYPE =5 AND'#$D#$A+
'          D.RDB$DEPENDED_ON_NAME IN @OBJECT'#$D#$A+
'    UNION'#$D#$A+
'    SELECT'#$D#$A+
'      D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,'#$D#$A+
'      D.RDB$DEPENDENT_NAME AS OBJECT_NAME'#$D#$A+
'    FROM RDB$DEPENDENCIES D'#$D#$A+
' join rdb$triggers TR ON  TR.rdb$trigger_name=D.RDB$DEPENDENT_NAME'#$D#$A+
'    WHERE D.RDB$DEPENDED_ON_TYPE IN (0,1) AND'#$D#$A+
'          D.RDB$DEPENDENT_TYPE =2 AND'#$D#$A+
'          TR.RDB$SYSTEM_FLAG=0 AND'#$D#$A+
'          D.RDB$DEPENDED_ON_NAME IN @OBJECT AND'#$D#$A+
'          NOT  TR.rdb$relation_name IN  @OBJECT'#$D#$A+
'    UNION'#$D#$A+
'   SELECT'#$D#$A+
'      CAST(7 AS SMALLINT) AS DEPENDENT_TYPE,'#$D#$A+
'      CC.rdb$constraint_name AS OBJECT_NAME'#$D#$A+
'    FROM RDB$DEPENDENCIES D'#$D#$A+
'     join rdb$triggers TR ON  TR.rdb$trigger_name=D.RDB$DEPENDENT_NAME'#$D#$A+
'     join rdb$check_constraints CC on CC.rdb$trigger_name=D.RDB$DEPENDENT_NAME'#$D#$A+
'    WHERE D.RDB$DEPENDED_ON_TYPE IN (0,1) AND'#$D#$A+
'          D.RDB$DEPENDENT_TYPE =2 AND'#$D#$A+
'          D.RDB$DEPENDED_ON_NAME IN @OBJECT AND'#$D#$A+
'          NOT  TR.rdb$relation_name IN  @OBJECT'#$D#$A+
'    UNION'#$D#$A+
'    SELECT'#$D#$A+                     //Computed Fields
'      CAST(3 AS SMALLINT) AS DEPENDENT_TYPE,'#$D#$A+
'      RF.RDB$RELATION_NAME AS OBJECT_NAME'#$D#$A+
''#$D#$A+
'    FROM RDB$DEPENDENCIES D'#$D#$A+
'      JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#$D#$A+
'      JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME'#$D#$A+
'    WHERE R.RDB$VIEW_BLR IS NULL AND'#$D#$A+
'          D.RDB$DEPENDENT_TYPE = 3 AND'#$D#$A+
'          D.RDB$DEPENDED_ON_NAME IN @OBJECT'#$D#$A+
'    UNION'#$D#$A+
'    SELECT'#$D#$A+                     //Views in fields
'      CAST(1 AS SMALLINT) AS DEPENDENT_TYPE,'#$D#$A+
'      RF.RDB$RELATION_NAME AS OBJECT_NAME'#$D#$A+
''#$D#$A+
'    FROM RDB$DEPENDENCIES D'#$D#$A+
'      JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#$D#$A+
'      JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME'#$D#$A+
'    WHERE NOT R.RDB$VIEW_BLR IS NULL AND'#$D#$A+
'          D.RDB$DEPENDENT_TYPE = 3 AND'#$D#$A+
'          D.RDB$DEPENDED_ON_NAME IN @OBJECT'

;


  SQL_GET_VIEW_USED_BY: array[0..0] of string = (
    'SELECT'#$D#$A+
    '  D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,'#$D#$A+
    '  D.RDB$DEPENDENT_NAME AS OBJECT_NAME,'#$D#$A+
    '  D.RDB$FIELD_NAME AS FIELD_NAME'#$D#$A+
    'FROM RDB$DEPENDENCIES D'#$D#$A+
    'WHERE D.RDB$DEPENDED_ON_TYPE = 0 AND'#$D#$A+
    '      D.RDB$DEPENDENT_TYPE <> 3 AND'#$D#$A+
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT'#$D#$A+
    ' '#$D#$A+
    'UNION ALL'#$D#$A+
    ' '#$D#$A+
    'SELECT'#$D#$A+
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,'#$D#$A+
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,'#$D#$A+
    '  RF.RDB$FIELD_NAME AS FIELD_NAME'#$D#$A+
    'FROM RDB$DEPENDENCIES D'#$D#$A+
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#$D#$A+
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME'#$D#$A+
    'WHERE R.RDB$VIEW_BLR IS NULL AND'#$D#$A+
    '      D.RDB$DEPENDENT_TYPE = 3 AND'#$D#$A+
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT'#$D#$A+

    'UNION ALL'#$D#$A+
    ' '#$D#$A+
    'SELECT DISTINCT'#$D#$A+
    '  CAST(1 AS SMALLINT) AS DEPENDENT_TYPE,'#$D#$A+
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,'#$D#$A+
    '  RF.RDB$FIELD_NAME AS FIELD_NAME'#$D#$A+
    'FROM RDB$DEPENDENCIES D'#$D#$A+
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#$D#$A+
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME'#$D#$A+
    'WHERE NOT R.RDB$VIEW_BLR IS NULL AND'#$D#$A+
    '      D.RDB$DEPENDENT_TYPE = 3 AND'#$D#$A+
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT'

    );

  SQL_GET_VIEW_USES:array[0..0] of string =(
'SELECT'#$D#$A+
'  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,'#$D#$A+
'  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,'#$D#$A+
'  D.RDB$FIELD_NAME AS FIELD_NAME'#$D#$A+
'FROM RDB$DEPENDENCIES D'#$D#$A+
'WHERE D.RDB$DEPENDENT_TYPE = 1 AND'#$D#$A+
'      D.RDB$DEPENDENT_NAME = :OBJECT'#$D#$A+
''#$D#$A+
'UNION ALL'#$D#$A+
''#$D#$A+
'SELECT'#$D#$A+
'  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,'#$D#$A+
'  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,'#$D#$A+
'  D.RDB$FIELD_NAME AS FIELD_NAME'#$D#$A+
'FROM RDB$DEPENDENCIES D'#$D#$A+
'  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#$D#$A+
'  JOIN RDB$RELATIONS R ON D.RDB$DEPENDED_ON_NAME=R.RDB$RELATION_NAME'#$D#$A+
'WHERE D.RDB$DEPENDENT_TYPE = 3 AND'#$D#$A+
'      RF.RDB$RELATION_NAME = :OBJECT'#$D#$A+
'      AND  R.RDB$VIEW_BLR IS NULL'#$D#$A+
''#$D#$A+
'UNION ALL'#$D#$A+
''#$D#$A+
'SELECT'#$D#$A+
'   CAST(1 AS SMALLINT),'#$D#$A+
'   V.RDB$RELATION_NAME AS OBJECT_NAME,'#$D#$A+
'   D.RDB$FIELD_NAME AS FIELD_NAME'#$D#$A+
''#$D#$A+
' FROM    RDB$VIEW_RELATIONS V'#$D#$A+
'   JOIN  RDB$RELATIONS R ON R.RDB$RELATION_NAME = V.RDB$RELATION_NAME'#$D#$A+
'   LEFT JOIN  RDB$DEPENDENCIES D ON D.RDB$DEPENDED_ON_NAME=V.RDB$VIEW_NAME'#$D#$A+
''#$D#$A+
' WHERE   V.RDB$VIEW_NAME=:OBJECT'#$D#$A+
' and  NOT R.RDB$VIEW_BLR IS NULL'#$D#$A+
'UNION '#$D#$A+

'SELECT'#$D#$A+ // Для зависимостей вида поле - селект из
'  CAST(1 AS SMALLINT),'#$D#$A+
'  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,'#$D#$A+
'  D.RDB$FIELD_NAME AS FIELD_NAME'#$D#$A+
''#$D#$A+
'FROM RDB$DEPENDENCIES D'#$D#$A+
'  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#$D#$A+
'  JOIN RDB$RELATIONS R ON D.RDB$DEPENDED_ON_NAME=R.RDB$RELATION_NAME'#$D#$A+
'WHERE D.RDB$DEPENDENT_TYPE = 3 AND'#$D#$A+
'      RF.RDB$RELATION_NAME = :OBJECT'#$D#$A+
'      AND  NOT R.RDB$VIEW_BLR IS NULL'

 );


{  SQL_GET_VIEW_USES: array[0..17] of string = (
    'SELECT',
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDENT_TYPE = 1 AND',
    '      D.RDB$DEPENDENT_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    'WHERE D.RDB$DEPENDENT_TYPE = 3 AND',
    '      RF.RDB$RELATION_NAME = :OBJECT'



    );
 }
// P R O C E D U R E S

  SQL_GET_PROCEDURE_USED_BY: array[0..32] of string = (
    'SELECT',
    '  D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDENT_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDED_ON_TYPE = 5 AND',
    '      D.RDB$DEPENDENT_TYPE <> 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  RF.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME',
    'WHERE R.RDB$VIEW_BLR IS NULL AND',
    '      D.RDB$DEPENDENT_TYPE = 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT',

    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(1 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  RF.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME',
    'WHERE  R.RDB$VIEW_BLR IS NOT NULL AND D.RDB$DEPENDENT_TYPE = 3 AND',
    '      D.RDB$DEPENDED_ON_NAME=:OBJECT'



    );

  SQL_GET_PROCEDURE_USES: array[0..17] of string = (
    'SELECT',
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDENT_TYPE = 5 AND',
    '      D.RDB$DEPENDENT_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    'WHERE D.RDB$DEPENDENT_TYPE = 3 AND',
    '      RF.RDB$RELATION_NAME = :OBJECT');

// T R I G G E R S

  SQL_GET_TRIGGER_USES: array[0..17] of string = (
    'SELECT',
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDENT_TYPE = 2 AND',
    '      D.RDB$DEPENDENT_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  D.RDB$DEPENDED_ON_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDED_ON_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    'WHERE D.RDB$DEPENDENT_TYPE = 3 AND',
    '      RF.RDB$RELATION_NAME = :OBJECT');

// G E N E R A T O R S

  SQL_GET_GENERATOR_USED_BY: array[0..20] of string = (
    'SELECT',
    '  D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDENT_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDED_ON_TYPE = ''%s'' AND',
    '      D.RDB$DEPENDENT_TYPE <> 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  RF.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME',
    'WHERE R.RDB$VIEW_BLR IS NULL AND',
    '      D.RDB$DEPENDENT_TYPE = 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT');

// E X C E P T I O N S

  SQL_GET_EXCEPTION_USED_BY: array[0..6] of string = (
    'SELECT',
    '  D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDENT_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDED_ON_TYPE = 7 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT');

// F U N C T I O N S

  SQL_GET_FUNCTION_USED_BY: array[0..0] of string = (
    'SELECT'#13#10+
    '  D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,'#13#10+
    '  D.RDB$DEPENDENT_NAME AS OBJECT_NAME,'#13#10+
    '  D.RDB$FIELD_NAME AS FIELD_NAME'#13#10+
    'FROM RDB$DEPENDENCIES D'#13#10+
    'WHERE D.RDB$DEPENDED_ON_TYPE IN (14,15) AND'#13#10+      //14 - IB, 15 - FB
    '      D.RDB$DEPENDENT_TYPE <> 3 AND'#13#10+
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT'#13#10#13#10+
    'UNION ALL'#13#10#13#10+
    'SELECT'#13#10+
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,'#13#10+
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,'#13#10+
    '  RF.RDB$FIELD_NAME AS FIELD_NAME'#13#10+
    'FROM RDB$DEPENDENCIES D'#13#10+
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME'#13#10+
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME'#13#10+
    'WHERE R.RDB$VIEW_BLR IS NULL AND'#13#10+
    '      D.RDB$DEPENDENT_TYPE = 3 AND'#13#10+
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT'
    );

  SQL_GET_FUNCTION_USED_BY2: array[0..0] of string = (
    'SELECT'#13#10+
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,'#13#10+
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,'#13#10+
    '  RF.RDB$FIELD_NAME AS FIELD_NAME,'#13#10+
    '  F.RDB$COMPUTED_SOURCE AS SOURCE'#13#10+
    'FROM RDB$RELATION_FIELDS RF'#13#10+
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE'#13#10+
    'WHERE RF.RDB$VIEW_CONTEXT IS NULL AND'#13#10+
    '      F.RDB$COMPUTED_SOURCE CONTAINING :OBJECT');

  SQL_GET_FUNCTION_USED_BY3: array[0..0] of string = (
    'SELECT'#13#10+
    '  CAST(1 AS SMALLINT) AS DEPENDENT_TYPE,'#13#10+
    '  R.RDB$RELATION_NAME AS OBJECT_NAME,'#13#10+
    '  CAST('' '' AS VARCHAR(1)) AS FIELD_NAME,'#13#10+
    '  R.RDB$VIEW_SOURCE AS SOURCE'#13#10+
    'FROM RDB$RELATIONS R'#13#10+
    'WHERE R.RDB$VIEW_SOURCE CONTAINING :OBJECT'#13#10+
    'UNION ALL'#13#10+
    'SELECT'#13#10+
    '  CAST(2 AS SMALLINT) AS DEPENDENT_TYPE,'#13#10+
    '  T.RDB$TRIGGER_NAME AS OBJECT_NAME,'#13#10+
    '  CAST('' '' AS VARCHAR(1)) AS FIELD_NAME,'#13#10+
    '  T.RDB$TRIGGER_SOURCE AS SOURCE'#13#10+
    'FROM RDB$TRIGGERS T'#13#10+
    'WHERE T.RDB$TRIGGER_SOURCE CONTAINING :OBJECT'#13#10+
    'UNION ALL'#13#10+
    'SELECT'#13#10+
    '  CAST(5 AS SMALLINT) AS DEPENDENT_TYPE,'#13#10+
    '  P.RDB$PROCEDURE_NAME AS OBJECT_NAME,'#13#10+
    '  CAST('' '' AS VARCHAR(1)) AS FIELD_NAME,'#13#10+
    '  P.RDB$PROCEDURE_SOURCE AS SOURCE'#13#10+
    'FROM RDB$PROCEDURES P'#13#10+
    'WHERE P.RDB$PROCEDURE_SOURCE CONTAINING :OBJECT');

// F I L T E R S

  SQL_GET_FILTER_USED_BY: array[0..20] of string = (
    'SELECT',
    '  D.RDB$DEPENDENT_TYPE AS DEPENDENT_TYPE,',
    '  D.RDB$DEPENDENT_NAME AS OBJECT_NAME,',
    '  D.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    'WHERE D.RDB$DEPENDED_ON_TYPE = 16 AND',
    '      D.RDB$DEPENDENT_TYPE <> 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT',
    ' ',
    'UNION ALL',
    ' ',
    'SELECT',
    '  CAST(0 AS SMALLINT) AS DEPENDENT_TYPE,',
    '  RF.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  RF.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$DEPENDENCIES D',
    '  JOIN RDB$RELATION_FIELDS RF ON RF.RDB$FIELD_SOURCE = D.RDB$DEPENDENT_NAME',
    '  JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME',
    'WHERE R.RDB$VIEW_BLR IS NULL AND',
    '      D.RDB$DEPENDENT_TYPE = 3 AND',
    '      D.RDB$DEPENDED_ON_NAME = :OBJECT');


// -----------------------------------------------------------------------------


  SQL_GET_USERS_FROM_PRIVILEGES: array[0..3] of string = (
    'SELECT DISTINCT',
    '  UP.RDB$USER AS USER_NAME',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$PRIVILEGE <> ''M'') AND (UP.RDB$USER_TYPE = 8)');

  SQL_GET_GRANTS_ON: array[0..6] of string = (
    'SELECT',
    '  RDB$RELATION_NAME AS OBJECT_NAME,',
    '  RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  RDB$PRIVILEGE AS PRIVILEGE,',
    '  RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$USER_PRIVILEGES',
    'WHERE RDB$USER = :USER_NAME');

  SQL_GET_GRANTS_ON_FOR_VIEW: array[0..7] of string = (
    'SELECT',
    '  UP.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  UP.RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  UP.RDB$PRIVILEGE AS PRIVILEGE,',
    '  UP.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$USER_TYPE = 1) AND',
//    '      (UP.RDB$FIELD_NAME IS NULL) AND',
    '      (UP.RDB$USER = :USER_NAME)');

  SQL_GET_GRANTS_ON_FOR_PROCEDURE: array[0..7] of string = (
    'SELECT',
    '  UP.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  UP.RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  UP.RDB$PRIVILEGE AS PRIVILEGE,',
    '  UP.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$USER_TYPE = 5) AND',
    '      (UP.RDB$USER = :USER_NAME)');

  SQL_GET_GRANTS_ON_FOR_TRIGGER: array[0..7] of string = (
    'SELECT',
    '  UP.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  UP.RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  UP.RDB$PRIVILEGE AS PRIVILEGE,',
    '  UP.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$USER_TYPE = 2) AND',
    '      (UP.RDB$USER = :USER_NAME)');

  SQL_GET_GRANTS_ON_FOR_ROLE: array[0..7] of string = (
    'SELECT',
    '  UP.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  UP.RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  UP.RDB$PRIVILEGE AS PRIVILEGE,',
    '  UP.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$USER_TYPE = 13) AND',
    '      (UP.RDB$USER = :USER_NAME)');

  SQL_GET_GRANTS_ON_FOR_USER: array[0..7] of string = (
    'SELECT',
    '  UP.RDB$RELATION_NAME AS OBJECT_NAME,',
    '  UP.RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  UP.RDB$PRIVILEGE AS PRIVILEGE,',
    '  UP.RDB$FIELD_NAME AS FIELD_NAME',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$USER_TYPE = 8) AND',
    '      (UP.RDB$USER = :USER_NAME)');

  SQL_GRANT_TABLE: array[0..0] of string = (
    'GRANT %s ON TABLE %s TO %s');

  SQL_GRANT_TABLE_WGO: array[0..0] of string = (
    'GRANT %s ON TABLE %s TO %s WITH GRANT OPTION');

  SQL_GRANT_TABLE_FIELD: array[0..0] of string = (
    'GRANT %s (%s) ON TABLE %s TO %s');

  SQL_GRANT_TABLE_FIELD_WGO: array[0..0] of string = (
    'GRANT %s (%s) ON TABLE %s TO %s WITH GRANT OPTION');

  SQL_GRANT_PROCEDURE: array[0..0] of string = (
    'GRANT EXECUTE ON PROCEDURE %s TO %s');

  SQL_GRANT_PROCEDURE_WGO: array[0..0] of string = (
    'GRANT EXECUTE ON PROCEDURE %s TO %s WITH GRANT OPTION');

  SQL_REVOKE_TABLE: array[0..0] of string = (
    'REVOKE %s ON TABLE %s FROM %s');

  SQL_REVOKE_TABLE_WGO: array[0..0] of string = (
    'REVOKE GRANT OPTION FOR %s ON TABLE %s FROM %s');

  SQL_REVOKE_TABLE_FIELD: array[0..0] of string = (
    'REVOKE %s (%s) ON TABLE %s FROM %s');

  SQL_REVOKE_TABLE_FIELD_WGO: array[0..0] of string = (
    'REVOKE GRANT OPTION FOR %s (%s) ON TABLE %s FROM %s');

  SQL_REVOKE_PROCEDURE: array[0..0] of string = (
    'REVOKE EXECUTE ON PROCEDURE %s FROM %s');

  SQL_REVOKE_PROCEDURE_WGO: array[0..0] of string = (
    'REVOKE GRANT OPTION FOR EXECUTE ON PROCEDURE %s FROM %s');

  SQL_GET_GRANTS_FOR_TABLE: array[0..10] of string = (
    'SELECT',
    '  UP.RDB$PRIVILEGE AS PRIVILEGE,',
    '  UP.RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  UP.RDB$USER AS USER_NAME,',
    '  UP.RDB$USER_TYPE AS USER_TYPE',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$RELATION_NAME = ''%s'') AND',
    '      (RDB$OBJECT_TYPE = 0) AND',
    '      (UP.RDB$FIELD_NAME IS NULL) AND',
    '      (UP.RDB$USER <> ''SYSDBA'')',
    'ORDER BY UP.RDB$USER_TYPE DESC, UP.RDB$USER ASC');

  SQL_GET_GRANTS_FOR_PROCEDURE: array[0..10] of string = (
    'SELECT',
    '  UP.RDB$PRIVILEGE AS PRIVILEGE,',
    '  UP.RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  UP.RDB$USER AS USER_NAME,',
    '  UP.RDB$USER_TYPE AS USER_TYPE',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$RELATION_NAME = ''%s'') AND',
    '      (RDB$OBJECT_TYPE = 5) AND',
    '      (UP.RDB$FIELD_NAME IS NULL) AND',
    '      (UP.RDB$USER <> ''SYSDBA'')',
    'ORDER BY UP.RDB$USER_TYPE DESC, UP.RDB$USER ASC');

  SQL_GET_GRANTS_FOR_ROLE: array[0..10] of string = (
    'SELECT',
    '  UP.RDB$PRIVILEGE AS PRIVILEGE,',
    '  UP.RDB$GRANT_OPTION AS GRANT_OPTION,',
    '  UP.RDB$USER AS USER_NAME,',
    '  UP.RDB$USER_TYPE AS USER_TYPE',
    'FROM RDB$USER_PRIVILEGES UP',
    'WHERE (UP.RDB$RELATION_NAME = ''%s'') AND',
    '      (RDB$OBJECT_TYPE = 13) AND',
    '      (UP.RDB$FIELD_NAME IS NULL) AND',
    '      (UP.RDB$USER <> ''SYSDBA'')',
    'ORDER BY UP.RDB$USER_TYPE DESC, UP.RDB$USER ASC');

// -----------------------------------------------------------------------------

  SQL_GET_USERS_FROM_SECURITY: array[0..6] of string = (
    'SELECT',
    '  U.USER_NAME,',
    '  U.PASSWD,',
    '  U.FIRST_NAME,',
    '  U.MIDDLE_NAME,',
    '  U.LAST_NAME',
    'FROM USERS U');

  {SQL Generator}
  SSelectTemplate = 'SELECT T.* FROM %s T';
  SSelectWithDB_KEYTemplate = 'SELECT T.RDB$DB_KEY, T.* FROM %s T';    
  
  SQL_INSERT_SECURITY: array[0..3] of string = (
    'INSERT INTO USERS',
    '(USER_NAME, PASSWD, FIRST_NAME, MIDDLE_NAME, LAST_NAME)',
    'VALUES',
    '(''%s'', ''%s'', ''%s'', ''%s'', ''%s'')');

  SQL_UPDATE_SECURITY: array[0..6] of string = (
    'UPDATE USERS U',
    'SET',
      'U.PASSWD = ''%s'',',
      'U.FIRST_NAME = ''%s'',',
      'U.MIDDLE_NAME = ''%s'',',
      'U.LAST_NAME = ''%s''',
    'WHERE U.USER_NAME = ''%s''');

  SQL_DELETE_SECURITY: array[0..1] of string = (
    'DELETE FROM USERS U',
    'WHERE U.USER_NAME = ''%s''');

  SQL_INIT_QUERY_FIELDS1: array[0..28] of string = (
    'SELECT',
    '  F.RDB$FIELD_NAME AS OBJECT_NAME,',
    '  F.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  F.RDB$DEFAULT_SOURCE AS DEFAULT_EXPRESSION,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  0  AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$VALIDATION_SOURCE AS CHECK_CONSTRAINT,',
    '  F.RDB$DIMENSIONS AS ARRAY_DIM,',
    '  F.RDB$COMPUTED_SOURCE AS COMPUTED_SOURCE,',
    '  RF.RDB$FIELD_NAME AS F_FIELD_NAME,',
    '  RF.RDB$RELATION_NAME AS F_TABLE_NAME,',
    '  RF.RDB$DESCRIPTION AS F_DESCRIPTION,',
    '  RF.RDB$NULL_FLAG AS F_NOT_NULL,',
    '  RF.RDB$DEFAULT_SOURCE AS F_DEFAULT_EXPRESSION,',
    '  RF.RDB$FIELD_SOURCE AS F_BASED_ON_DOMAIN,',
    '  RF.RDB$COLLATION_ID AS F_COLLATE_ID',
    'FROM RDB$RELATION_FIELDS RF',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE',
    'WHERE RF.RDB$RELATION_NAME = :RELATION_NAME AND',
    '      RF.RDB$FIELD_NAME = :FIELD_NAME');

  SQL_INIT_QUERY_FIELDS3: array[0..28] of string = (
    'SELECT',
    '  F.RDB$FIELD_NAME AS OBJECT_NAME,',
    '  F.RDB$DESCRIPTION AS DESCRIPTION,',
    '  F.RDB$FIELD_TYPE AS FIELD_TYPE_ID,',
    '  F.RDB$NULL_FLAG AS NOT_NULL,',
    '  F.RDB$DEFAULT_SOURCE AS DEFAULT_EXPRESSION,',
    '  F.RDB$FIELD_LENGTH AS FIELD_LENGTH_,',
    '  F.RDB$CHARACTER_LENGTH AS LENGTH_,',
    '  F.RDB$FIELD_PRECISION AS PRECISION_,',
    '  F.RDB$FIELD_SCALE AS SCALE,',
    '  F.RDB$CHARACTER_SET_ID AS CHARSET_ID,',
    '  F.RDB$COLLATION_ID AS COLLATE_ID,',
    '  F.RDB$FIELD_SUB_TYPE AS SUB_TYPE_ID,',
    '  F.RDB$SEGMENT_LENGTH AS SEGMENT_SIZE,',
    '  F.RDB$SYSTEM_FLAG AS SYSTEM_FLAG,',
    '  F.RDB$VALIDATION_SOURCE AS CHECK_CONSTRAINT,',
    '  F.RDB$DIMENSIONS AS ARRAY_DIM,',
    '  F.RDB$COMPUTED_SOURCE AS COMPUTED_SOURCE,',
    '  RF.RDB$FIELD_NAME AS F_FIELD_NAME,',
    '  RF.RDB$RELATION_NAME AS F_TABLE_NAME,',
    '  RF.RDB$DESCRIPTION AS F_DESCRIPTION,',
    '  RF.RDB$NULL_FLAG AS F_NOT_NULL,',
    '  RF.RDB$DEFAULT_SOURCE AS F_DEFAULT_EXPRESSION,',
    '  RF.RDB$FIELD_SOURCE AS F_BASED_ON_DOMAIN,',
    '  RF.RDB$COLLATION_ID AS F_COLLATE_ID',
    'FROM RDB$RELATION_FIELDS RF',
    '  JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE',
    'WHERE RF.RDB$RELATION_NAME = :RELATION_NAME AND',
    '      RF.RDB$FIELD_NAME = :FIELD_NAME');


implementation

end.

